#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\AuthController::index

test_page:
    path: /test_page
    controller: App\Controller\AuthController::testPage
